### ISSUE TITLE
Website buttons on certain pages dont fully display embedded image

### ISSUE THREAD

**Issue by wicknix** [rmottola/Arctic-Fox#1]
This should have the facebook logo displayed in it.

![screen shot 2018-10-10 at 11 13 05 pm](https://user-images.githubusercontent.com/39230578/46780455-6570e800-cd0c-11e8-9eb9-3ab537a853c2.png)

**Comment by rmottola** [comment]
This appears to work for me in my latest build.. and for you? (testing heavily my latest ContentPolicy changes... so testing random websites and noticed)

**Comment by wicknix** [comment]
Still flaky on a few sites for me. Probably slight differences in our installed packages for our build environments.

**Comment by rmottola** [comment]
Do you have references to these flaky site so we can try who .18 performs?

**Comment by rmottola** [comment]
Works for me quite reliably now.
