### ISSUE TITLE
Youtube thinks that my iMac is a mobile phone

### ISSUE THREAD

**Issue by Windows-10-8** [rmottola/Arctic-Fox#110]
Hello, I have an iMac with Mac OS Lion.
I installed Arctic Fox.
When I go on youtube, it redirects me to m.youtube.com and not to youtube.com.
Youtube thinks that I'm on a mobile phone.

Any fix?

**Comment by wicknix** [comment]
We did that because the new youtube layout is very slow. However if you want to change it back go ahead.
Open about:config and type youtube in the search box. Double click the mobile user agent string, delete it, and add in whatever user agent you want.

**Comment by Windows-10-8** [comment]
Thanks for reply.
There isn't a method to restore the old layout to make youtube desktop faster?

**Comment by 3oheicrw** [comment]
This is because of user agent override. You should try invidious instead, youtube is not quite usable on this browser.

**Comment by rmottola** [comment]
No, unfortunately google removed the old layout. Actually, even the current desktop layout used by AF is legacy, although it works. Somewhen that one will break too.

**Comment by rmottola** [comment]
Disguising as mobile should be removed now from the useragent override. Google definitively removed the mobile version thus even old links do not work anymore.
