### ISSUE TITLE
On Windows 8.1 64 bit all websites are "This connection is untrusted"

### ISSUE THREAD

**Issue by 3oheicrw** [rmottola/Arctic-Fox#118]
I'm using @roytam1's build for Windows XP 64 bit on my Windows 8.1 64 bit. I just want to test some websites with a Pale Moon 27 based browser and since you provided no binary builds for Windows and I don't want to build it myself I reused @roytam1's 64 bit build for Windows XP. This alone could be a problem. But I can't contact @roytam1 because I can't register at msfn and he has all of his repos not open to create new issues so I created an issue here. Hopefully both of you will see.

p/s: I have to run his palemoon.exe in Windows 7 compatibility mode otherwise the buttons on the top right of the window will not be shown, there will be only a pure black area and you will have to exit the browser via it menu.

**Comment by rmottola** [comment]
I don't provide Windows builds, I can't build myself, it is @roytam1's work, you should please open a bug on his fork.

For problems reproduceable on Mac or Windows, this place is fine.

**Comment by 3oheicrw** [comment]
> I don't provide Windows builds, I can't build myself, it is @roytam1's work, you should please open a bug on his fork.
> 
> For problems reproduceable on Mac or Windows, this place is fine.

None of his repos enabled submitting issues. There is no way to contact him other than on the msfn forum which I always have problems registering :smile:
