### ISSUE TITLE
ArcticFox v40.0 crashes on Mtn Lion

### ISSUE THREAD

**Issue by RobK88** [rmottola/Arctic-Fox#120]
ArcticFox v40.0 crashes on Mtn Lion upon launch.  Both the 64-bit and 32-bit versions crash.
ArcticFox 39.2 runs well on Mtn Lion.

Here is part of the crash log:

Process:         arcticfox [87523]
Path:            /Applications/ArcticFox.app/Contents/MacOS/arcticfox
Identifier:      org.mozilla.arctic fox
Version:         40.0 (4022.10.15)
Code Type:       X86-64 (Native)
Parent Process:  launchd [138]
User ID:         501

Date/Time:       2022-10-15 19:56:23.869 -0400
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10

Interval Since Last Report:          600837 sec
Crashes Since Last Report:           1425
Per-App Interval Since Last Report:  14 sec
Per-App Crashes Since Last Report:   3
Anonymous UUID:                     xxxxx

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

**Comment by RobK88** [comment]
I finally got version 40.0 (64-bit) to run on Mtn Lion.  I had to run arcticFox a couple of times!  And during one of the attempts it asked me to refresh ArcticFox.  I said YES! Now, no more crashing on start-up. 

Perhaps the config file has changed.

**Comment by rmottola** [comment]
That is a "known issue" that pops up for some people, it was theoretically solved in 39.2 already. You have some preferences left that shouldn't exist (not the profile). Once convinced, it should work an be stable. At least it is for me.
A refresh is good - in 40.0 it should work, before you could risk loosing your profile, fixed that.
If it continues to run, please confirm and close.

**Comment by RobK88** [comment]
Yes, ArcticFox has stabilized and is now launching fine on Mtn Lion without crashing.  

I will close off this ticket even though I suspect that there is still a big somewhere in v40.0.  The workaround is to keep launching ArcticFox after it crashes until it stabilizes and launches properly without crashing.
