### ISSUE TITLE
ArctIcFox v40.0 Crash on Import Bookmarks Window

### ISSUE THREAD

**Issue by RobK88** [rmottola/Arctic-Fox#121]
Steps to reproduce:

1.  Install ArcticFox on a Mac for the VERY first time
2. Arctic Fox will ask if you want to import bookmarks etc from other browsers, etc
3. Click the CANCEL button
4. Arctic Fox will CRASH

Crash happened on Lion (10.7)

**Comment by rmottola** [comment]
Would you mind trying 40.1? there were some fixes in direction, but apparently Mac has some specific issues compared to Linux

**Comment by rmottola** [comment]
40.1 fixes it for me, got no reply though... will close this soon.
