### ISSUE TITLE
Wiki page does not exist

### ISSUE THREAD

**Issue by macbian-linux** [rmottola/Arctic-Fox#123]
Not sure if this is the right place to put this, but the wiki page (and with it the precompiled binaries referenced in README.md) just displays this: 
![image](https://user-images.githubusercontent.com/104112636/185770175-9e6f7985-da39-47d5-a558-a7b54f117724.png)

**Comment by rmottola** [comment]
You are looking at a fork of the project - my fork. The wiki and binaries are supplied by the master project
https://github.com/wicknix/Arctic-Fox/wiki

In the future we will attempt a switch of the root project.
