### ISSUE TITLE
Build instructions for Linux ?

### ISSUE THREAD

**Issue by ScarFez** [rmottola/Arctic-Fox#124]
Any hope for build instructions ?

**Comment by kth5** [comment]
Maybe this PKGBUILD helps?

https://github.com/kth5/archpower/tree/master/arcticfox

**Comment by rmottola** [comment]
Building is very similar to PaleMoon or FireFox itself.... create your .mozconfig (there are several examples), customize it and build with "mach build". You will need several dependencies, depending on your configuration, for most you will be guided.
Only caveat to begin with is: autoconfig 2.13 and python 2.7 are required.

**Comment by vl-ms** [comment]
Somebody should just fix the existing link to Pale Moon documentation in the README.md that got broken some time ago. I'm too lazy to setup my own branch for this tho. The new link is http://developer.palemoon.org/build/linux/ and http://developer.palemoon.org/build/windows/ for linux and windows respectively.

**Comment by xplshn** [comment]
I made an AppImage of the 42.0 release, its here: https://github.com/xplshn/RAWFILES/releases/download/release/Arcticfox-x86_64.AppImage

You can check the contents of any app image by appending this argument --appimage-extract and it will decompress itself to a squashfs-root dir. Which would have all the binaries of Arcticfox under usr/arcticfox.

**Comment by rmottola** [comment]
I made a new Wiki entry so to allow having specific AF build instructions.
There I also linked useful PaleMoon and TenFourFox resources, after having updated as @vl-ms the PM links.

https://github.com/rmottola/Arctic-Fox/wiki/Build-Instructions

**Comment by xplshn** [comment]
Thanks, I figured it out. I made an appimage. It will be published at appimagehub when its approved
