### ISSUE TITLE
[Building] Remove or patch mach script

### ISSUE THREAD

**Issue by donmor** [rmottola/Arctic-Fox#127]
`mach` requires python2.7, which has been abandoned. We should either let it use python3.x, or just replace it with classic gnu autotools or cmake.

**Comment by rmottola** [comment]
the task is too big... it took firefox years to support python 3.
I have no intention of diverging from their build system, so make/cmake are excluded sorry.

You could try using python3, in theory several support patches were imported, but I don't know the actual switch

**Comment by xplshn** [comment]
Seems like this issue should be re-opened

**Comment by rmottola** [comment]
https://github.com/rmottola/Arctic-Fox/issues/226
