### ISSUE TITLE
Update "prebuilt binary" download links to include newer versions / More in-depth tutorial to "build" new versions on Mac?

### ISSUE THREAD

**Issue by green3554** [rmottola/Arctic-Fox#134]
The tutorial to "build on MacOSX" is very confusing to me, I don't understand it. Could someone create a more in-depth tutorial, or just update the downloads on the Wiki page for the new version? Right now it only has 27.11.0 for Mac. 
Also it states on the Wiki that current release builds can be found at https://github.com/wicknix/Arctic-Fox/releases , but the link is blank.

Thank you!

**Comment by gatk555** [comment]
I came here with the same problem.  If I have to install build tools on 10.6 to update, I may prefer the alternative and switch to Linux.  Many thanks to the Arctic Fox developers for keeping this old iMac going so long.

**Comment by wicknix** [comment]
All prebuilt binaries are available from the releases link on the main page.
https://github.com/rmottola/Arctic-Fox/releases

**Comment by green3554** [comment]
Ah! It seems the link from https://github.com/rmottola/Arctic-Fox/wiki/Downloads is outdated. Many thanks!
