### ISSUE TITLE
ArcticFox 41.0 crashes on Snow Leopard.

### ISSUE THREAD

**Issue by largefield-ohara** [rmottola/Arctic-Fox#135]
ArcticFox 41.0 crashes when launched from Snow Leopard (macOS 10.6).
The error message is as follows:

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/Arctic Fox/ArcticFox.app/Contents/MacOS/arcticfox
  Reason: image not found

libc++ is a library supported since Mavericks (macOS 10.9), so Snow Leopard does not have it.

**Comment by green3554** [comment]
I'm having the same issue, running Snow Leopard 10.6.8

**Comment by gatk555** [comment]
Exactly the same here.  40.1 is OK.

**Comment by rmottola** [comment]
I do not build on mavericks and I think @wicknix neither. i do a native build on 10.6 and on 10.7.
Are you running the 32bit or 64bit versions? We did different builds from different users.

**Comment by rmottola** [comment]
I wonder if a dependency on MacPorts is left in.... @wicknix do you have the environment coming from macports, do you?

**Comment by rmottola** [comment]
@wicknix I think the issue might be the "copy file" step mentioned in the Distribute step ... do you perform something similar in your builds?
https://github.com/classilla/tenfourfox/wiki/HowToBuildFPR

**Comment by largefield-ohara** [comment]
42.0 also did not start on snow leopard, but after installing libc++ using macports, it started. To check the launch, I used arcticfox-42.0.mac64-10.6.dmg in Assets.

**Comment by wicknix** [comment]
Yes, you will need to include libc++.1.dylib and libc++abi.dylib in the .app and then use otool to relink them before you distribute for 10.6 _(not required for 10.7)._ Otherwise users that don't have macports and libc++ installed with just get crashes upon launch.

**Comment by rmottola** [comment]
Indeed, I do not relinked or packaged libc+++ from MacPorts. I will add it as separate file in the future.

**Comment by rmottola** [comment]
I was unable to adapt the TenFourFox link script, because I compile with clang and not gcc, so I do not have libgcc. I'll add a zip with the files for 10.6 64bit in the upcoming 42.1 release. Should be fine for 42.0.

**Comment by tskspree** [comment]
Same libc++.1.dylib error message when attempting to start 42.1

**Comment by tskspree** [comment]
Fixed the issue by installing xcode 3.2.6, macports 2.8.1 and then "sudo port install libcxx".

**Comment by rmottola** [comment]
This is fixed by installing the required libraries, either with macports or with the one provided e.g. here:
https://github.com/rmottola/Arctic-Fox/releases/tag/v42.1
