### ISSUE TITLE
rebasing on UXP 

### ISSUE THREAD

**Issue by brunomaximom** [rmottola/Arctic-Fox#142]
Any reason for not using UXP or forking new Pale Moon (or Basilisk for WebRTC support) and make it build on old macs and PPC Linux as well as ARM (I know they are now building on ARM)? Is that even possible with UXP?

**Comment by rmottola** [comment]
We build on ARM too.
UXP and PM development is opaque as is their licensing, so we streamlined many things and try to follow FF and TFF a long as it is feasible.
If you just need PM, then use New Moon or equivalent fork, this project would have no meaning.
