### ISSUE TITLE
Logo Idea and design

### ISSUE THREAD

**Issue by louies0623** [rmottola/Arctic-Fox#147]
English is not very good, please forgive me. 
Here's what I've modified from the old Firefox logo, along with some thoughts.

Logo and text
![Logo with text](https://github.com/rmottola/Arctic-Fox/assets/44593430/ba92faf9-5388-4e8f-b26b-9e5de03787ea)

Logo
![Logo](https://github.com/rmottola/Arctic-Fox/assets/44593430/51667970-195b-4229-a644-6a885e290b95)

Mac background
![Mac-install-background](https://github.com/rmottola/Arctic-Fox/assets/44593430/d4fa008f-09ff-48df-9773-7e4d6409d6a0)

About background
![About-background](https://github.com/rmottola/Arctic-Fox/assets/44593430/da54ae98-9c3c-4267-9564-64e57a4b23da)

Demo
![About-background-demo](https://github.com/rmottola/Arctic-Fox/assets/44593430/4222c492-2dd8-4c17-8016-4b7290ddc3a1)
![Mac-install-background-demo](https://github.com/rmottola/Arctic-Fox/assets/44593430/3674ef77-18b2-430d-a306-7b62380eeae6)

**Comment by rmottola** [comment]
Thank you for your ideas. I am indeed planning for the next major release (would be 44) some graphics update. I like the current logo, but I dislike the aliasing on the background of the ArcitcFox lettering.
I like your icon, it is very subdued... works fine perhaps on mac but not everywhere, I will play with it.

What did you design it in?

Your Arctic Fox lettering however in Courier-style is a little bit too plain, I liked the idea of a fantasy font with an icy feeling on it used by @wicknix, but it doesn't alias well on the dark background of the about box which I'd like to retain.

**Comment by rmottola** [comment]
@louies0623 are you still interested in working on this?

**Comment by louies0623** [comment]
A little bit. 
I designed it using illustrator. I wanted to use a calmer way to handle the font, but it is indeed a bit monotonous. To be honest, It’s just that the original logo font is a bit too fragmented. If the fragmentation is reduced, it will look better.

**Comment by louies0623** [comment]
According to your request, I have used the word "close" to the original one. Since I don't have the image files and the quality of the images I found is too poor, I had to redesign it myself.
![dfhdhdhd-03](https://github.com/rmottola/Arctic-Fox/assets/44593430/701699f9-5658-407a-b34a-a789e95d45b6)
![dfhdhdhd-04](https://github.com/rmottola/Arctic-Fox/assets/44593430/9ab91297-c241-414f-8897-2f757bfcd97d)


Info-Background.png
![Info-background](https://github.com/rmottola/Arctic-Fox/assets/44593430/1941bfe2-35b3-4aa7-b1bd-15f8a7b4fa55)


Text SVG
![Logo-text](https://github.com/rmottola/Arctic-Fox/assets/44593430/6bf39091-58eb-4d94-8ac0-8fab5d28601b)


Text with shadow PNG
![logo-shadow](https://github.com/rmottola/Arctic-Fox/assets/44593430/6f58221b-6f0d-4b4d-b635-fc32edd61437)

Full logo SVG
![Logo with text](https://github.com/rmottola/Arctic-Fox/assets/44593430/4513a357-7511-48fd-ae45-3dd7e61036a6)

Disk icon
PNG
![AF Disk-01-01](https://github.com/rmottola/Arctic-Fox/assets/44593430/445ebcae-0be6-4df4-82ab-704f512379c8)
SVG
![AF Disk-01-01](https://github.com/rmottola/Arctic-Fox/assets/44593430/25dbc7af-36d2-40f7-88df-067ac014e815)

**Comment by rmottola** [comment]
I think they look quite nice! We should check how they fit in the browser itself, did you try already?
Do you build your own AF?

I will try them at the next major release!

**Comment by louies0623** [comment]
I didn't try to build because I don't understand code, If you can, please give it a try; if you want to check whether the interface is configured well, you can close your eyes and calm down for ten seconds, and then look at it again. You will feel closer to the user than the first time you interact with it. This is me idea

**Comment by louies0623** [comment]
Supplement the side background of Windows installation.
Background
![dfhdhdhd-05](https://github.com/rmottola/Arctic-Fox/assets/44593430/f523f332-a100-4b9f-ad6e-d3af5d4bdd28)

Demo
![dfhdhdhd-06](https://github.com/rmottola/Arctic-Fox/assets/44593430/aa321d5e-abaf-4b72-8743-474c0e1397fe)

**Comment by rmottola** [comment]
Hi, I started a branch to test your work.

This is an image on my Linux setup. I only substituted images starting from your artwork, didn't try to adapt html or css yet.

![immagine](https://github.com/rmottola/Arctic-Fox/assets/12441935/8714849b-639c-450d-b692-77951de3b558)

**Comment by louies0623** [comment]
Thank you for your help, it looks good, I think I need to give a new 'about' background.

**Comment by rmottola** [comment]
This is instead what I get on mac

![image](https://github.com/rmottola/Arctic-Fox/assets/12441935/6248ba8e-85ec-4f16-a9bc-b0df8cd5f09b)

**Comment by rmottola** [comment]
> Supplement the side background of Windows installation. 

I actually don't know where the template for this is, I didn't find anything close in the branding section

**Comment by rmottola** [comment]
> Thank you for your help, it looks good, I think I need to give a new 'about' background.

Do you think? the white band is part of the CSS, not your image, I think it can be tweaked.

**Comment by rmottola** [comment]
I used your artwork to generate various images and changed the branding. Some ideas and feelings:

1. Overall idea looks quite good and solves also graphical glitches of the old logo
2. Old artwork had differentiation between icons and the specific "about" and "about with name" with a silhouette appearing in the start page seen in the mac screenshot. We may discuss what is best. Perhaps the text is not so good on the logo.
3. On both WindowMaker grey Dock icons and "modern" mac dock, the icon looks very subtle against the background. This is different from the more classic 10.6/10.7 dock. I don't know if it is bad or just need to get accustomed to it. Or maybe it is a little bit too icy and desaturated?
4. Mac disk image looks really nice!
5. mac uses icns, and I used Preview.app to work change them by copying data from individual 16,32,48,128 pixel images, I don't know a better way on current Mac. There used to be an ICNS tool. I must have done something wrong, look at the icons in the path
6. dmg icon is sitll old, but probably this is only a refresh issue, I changed things without doing a full clean build which takes a long time
7. I did not touch anything about windows ICO files
8. there are images in branding which I don't know what they do and where they appear, so don't know how to check and tweak them

**Comment by rmottola** [comment]
Unknown usage items:

- [ ] https://github.com/rmottola/Arctic-Fox/blob/new_logo/browser/branding/arcticfox/appname.bmp
- [ ] https://github.com/rmottola/Arctic-Fox/blob/new_logo/browser/branding/arcticfox/content/identity-icons-brand.png
- [ ] https://github.com/rmottola/Arctic-Fox/blob/new_logo/browser/branding/arcticfox/content/silhouette-40.svg
- [x] https://github.com/rmottola/Arctic-Fox/blob/new_logo/browser/branding/arcticfox/wizWatermark.bmp : is this the window installer perhaps?

**Comment by rmottola** [comment]
For reference, I found this in the Firefox dev guide:

`sips -z 32 32 icon_512x512.png --out firefox.iconset/icon_32x32.png`

```
mkdir firefox.iconset
mv icon_16x16.png firefox.iconset
mv icon_32x32.png firefox.iconset
mv icon_32x32@2x.png firefox.iconset
mv icon_64x64@2x.png firefox.iconset
mv icon_128x128.png firefox.iconset
mv icon_256x256 firefox.iconset
mv icon_256x256@2x.png firefox.iconset
mv icon_512x512.png firefox.iconset
mv icon_512x512@2x.png firefox.iconset
mv icon_1024x1024@2x.png firefox.iconset
iconutil -c icns firefox.iconset
```

**Comment by louies0623** [comment]
About Background.
This is the background with the squares removed and the blank background.
![dfhdhdhd-07](https://github.com/rmottola/Arctic-Fox/assets/44593430/99be3137-44c5-4286-bce9-c018e750803f)
![dfhdhdhd-08](https://github.com/rmottola/Arctic-Fox/assets/44593430/6ed9a02e-6e27-4aef-a70f-af651de97215)

about: page logo
![dfhdhdhd-09](https://github.com/rmottola/Arctic-Fox/assets/44593430/ee40576d-0d6b-49f8-b929-881ee9fd91bf)
[logo svg](https://github.com/rmottola/Arctic-Fox/assets/44593430/6bb479be-3279-4ee4-a15b-7201caae7357)

**Comment by louies0623** [comment]
For a background in dmg this is what I could find.
https://github.com/tauri-apps/tauri/issues/4669

**Comment by louies0623** [comment]
> * [ ]  https://github.com/rmottola/Arctic-Fox/blob/new_logo/browser/branding/arcticfox/wizWatermark.bmp : is this the window installer perhaps?


I guess it is

**Comment by rmottola** [comment]
@louies0623 I did a lot of progress and was able to recreate most images. I tweaked the about panel, fixed the installer icons. I prepared the window wizard, but cannot test it myself.

things look good, I think.
![image](https://github.com/rmottola/Arctic-Fox/assets/12441935/f04ea395-d2b2-4007-833b-8bd21cabb990)
![image](https://github.com/rmottola/Arctic-Fox/assets/12441935/abc5e93b-bcde-47ed-a9ea-7e6f827edb80)

Also the small disk icons are now all fine!

**Comment by rmottola** [comment]
I think we should update the document icons. I don't know if they are much used (perhaps only on URLs and HTML documents if the browser is set to default?) for both windows and Mac.  I don't find Linux image equivalent.
These are still the newmoon images!

![image](https://github.com/rmottola/Arctic-Fox/assets/12441935/91b6c3b2-35c8-4701-9515-b3fc8acf2864)

Would you like to make me a proposal?

**Comment by rmottola** [comment]
Given the new colors, I also tweaked the about box colors. Do you like it better?

![image](https://github.com/rmottola/Arctic-Fox/assets/12441935/1a514f59-5e31-4d8b-9778-2f8920c1569c)

**Comment by louies0623** [comment]
Amazing work ,I like it.

**Comment by louies0623** [comment]
> I think we should update the document icons. I don't know if they are much used (perhaps only on URLs and HTML documents if the browser is set to default?) for both windows and Mac. I don't find Linux image equivalent. These are still the newmoon images!
> 
> ![image](https://private-user-images.githubusercontent.com/12441935/297718728-91b6c3b2-35c8-4701-9515-b3fc8acf2864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTU0NzUsIm5iZiI6MTcwNjI1NTE3NSwicGF0aCI6Ii8xMjQ0MTkzNS8yOTc3MTg3MjgtOTFiNmMzYjItMzVjOC00NzAxLTk1MTUtYjNmYzhhY2YyODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3NDYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMmFkNjdlZWQ1NjgxOGVhMTNmMTgwY2VhM2VhMGQyOGY0YmQ2N2Y0NWU5ODQyOWZhN2FiOTcyMmZiNGRlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jgbzw4NJTIDlYHNJ_sOH_uL2ThXbQmbz3LB5Pk8Zoaw)
> 
> Would you like to make me a proposal?


png 
![AF File-01](https://github.com/rmottola/Arctic-Fox/assets/44593430/0aec0d4d-6cb8-49a7-95bd-f72957a6cdd6)

[SVG ](https://github.com/rmottola/Arctic-Fox/assets/44593430/78e057cb-538d-40f7-b7ee-afcaaef713e9)

**Comment by rmottola** [comment]
@louies0623 I converted your design into icon images... than you.
Next release will look cool!

**Comment by rmottola** [comment]
@roytam1 how do the new icons, logo and rest come out on windows? I replaced to the best... including the installer, but I don't know if you build it or it still builds.

**Comment by roytam1** [comment]
> @roytam1 how do the new icons, logo and rest come out on windows? I replaced to the best... including the installer, but I don't know if you build it or it still builds.

since I don't build installers I don't test that part, otherwise it works fine.

**Comment by louies0623** [comment]
> > @roytam1 how do the new icons, logo and rest come out on windows? I replaced to the best... including the installer, but I don't know if you build it or it still builds.
> 
> since I don't build installers I don't test that part, otherwise it works fine.

ok

**Comment by rmottola** [comment]
@louies0623 if you want to give me your full name I can cite you in the next announcement.

**Comment by louies0623** [comment]
No need, thank you very much. 😉

**Comment by rmottola** [comment]
Released!
