### ISSUE TITLE
Download link for 27.11.0 (32-bit Intel Mac) broken

### ISSUE THREAD

**Issue by rhisoc** [rmottola/Arctic-Fox#150]
I wanted to download the 27.11.0 version for 32-bit Intel Mac OS X 10.6, but that (Google Drive) download link is broken.

Another user [commented](https://github.com/rmottola/Arctic-Fox/issues/103) last year that (s)he could still access the link (but lamenting that legacy computers won't access GDrive). But now, in the past year, that file apparently went missing altogether.

**Comment by rmottola** [comment]
Sorry, such download links were provided by @wicknix
I removed the broken link, please use releases here: https://github.com/rmottola/Arctic-Fox/releases

**Comment by rmottola** [comment]
Are you willing to test a possible 10.6 32bit package, @rhisoc ? I am trying to built it myself now.

**Comment by rhisoc** [comment]
Yes, absolutely!

**Comment by rmottola** [comment]
It is not possible to upload big files here in issues, 43 is still in beta, I temporarily added it to the old release.
Please get it here @rhisoc :
https://github.com/rmottola/Arctic-Fox/releases/download/v42.1/arcticfox-43.0b1.en-US.mac.dmg.gz

maybe you need libc++ maybe not, please test and report back.

**Comment by rmottola** [comment]
@rhisoc you didn't give feedback. I released 43.0 in the meanwhile with an official 32bit binary. it works for me, does it for you?
Please let us know if you need libstdc++ or not.

I removed the temporary beta to avoid confusion.

**Comment by rmottola** [comment]
No feedback received. Link is provided, in case, reopen specific issues for 32bit.

**Comment by rhisoc** [comment]
Thanks, and sorry for not replying earlier. My powerpc is a side project for which I can only occasionally make time.

I have downloaded v43.0 and tried to install libc++ but I'm getting the following error when launching ArcticFox:

Library not loaded: /opt/local/lib/libcxx/libc++abi.1.dylib
Referenced from: /usr/lib/libc++.1.dylib
Reason: image not found

Is this something you/anyone can help with?

**Comment by rmottola** [comment]
@rhisoc  PowerPC ? We have no working release of PPC for AF, just a branch for 10.5. If you want to contribute, welcome.

For 10.6  Intel you either need MacPorts (needed anyway if you want to compile or tinker on your own stuff) or install the proper libc++ version I provide (32bit in your case, I suppose) into /usr/lib.
Read also here: https://github.com/rmottola/Arctic-Fox/issues/170 and  https://github.com/rmottola/Arctic-Fox/issues/162 

I created now a wiki page: https://github.com/rmottola/Arctic-Fox/wiki/libc---for-MacOS-10.6
