### ISSUE TITLE
Any chance we have a 43.0 for windows?

### ISSUE THREAD

**Issue by jasonliul** [rmottola/Arctic-Fox#163]
The changelog looks really tasty. :)

**Comment by rmottola** [comment]
Yes, it is tasty... I myself am unable to build for windows, unable to setup mingw to do so (tried).
@roytam1 does some builds done with MSVC, if he provides one, I will share it.

Or somebody joins the team here and helps windows ports.

**Comment by jasonliul** [comment]
Weird, i've noticed Roy used many patches from Arctic-Fox in his browser series.

**Comment by roytam1** [comment]
> i've noticed Roy used many patches from Arctic-Fox in his browser series.

I think rmottola knows this already. and this becomes my first tier for compilation test:
- first tier: my AF's winbuild branch (merges from here)
- second tier: my PM27-af-frontend branch (using all changes from 1st tier, glue to my PM27 branch with my changes done before)
- third tier: my PM27 master branch (using mostly back-end only changes from 2nd tier, with my efforts to glue old front-end with newer back-end together)

**Comment by roytam1** [comment]
> @roytam1 does some builds done with MSVC, if he provides one, I will share it.

if you don't mind having a dev build that is very close to merge point to master, I can post it. (since my winbuild branch doesn't merge to my master branch)

**Comment by jasonliul** [comment]
@roytam1 
Wow, you can't jump out just like ghost.
Well, happy to see U. :)

**Comment by rmottola** [comment]
> > @roytam1 does some builds done with MSVC, if he provides one, I will share it.
> 
> if you don't mind having a dev build that is very close to merge point to master, I can post it. (since my winbuild branch doesn't merge to my master branch)

No, I don't mind, I think it is convenient for users. Maybe I should have a way to tag "official release" build and "unofficial" builds. I think the unofficial branding is not currently supported.. as a small project it has not be considered, we didn't wan't all the mess PaleMoon has.

If there are some blocking things which need to be fixed to compile on windows, maybe I should import them. If you can update your fork against current master (it was based against the old repo I think and got lost in the Matt-to-Rick transition)

**Comment by jasonliul** [comment]
@rmottola 

>... as a small project

You should be more ambitious now, it's time to be more shining.
Since Google set limits to chromium clone, most of chromium based browser already EOL, Firefox family become much more attractive than before.

People are seeking something fresh, like: https://arc.net/
And the Firefox clone had a fresh one - Floorp(like Vivaldi face and function), now Midori also join Firefox.

Some old stuff reborn, SRWare Iron, Comodo Dragon suddenly update to 117.

Recently people also interest to ArtisBrowser (https://artistscope.com/artisbrowser/), that's really surprise me.

Arctic-Fox is much better than ArtisBrowser, support XP doesn't means only xp users,now people use it on win7/8.x, seems finally get boring about version number game.

Mypal68 (by Feodor2) also have many fans on win7/8x, even 10/11.

**Comment by roytam1** [comment]
> No, I don't mind, I think it is convenient for users.

uploaded to my server: http://o.rthost.win/gpc/files1.rt/arcticfox-43.0.win32-git-20231027.7z

**Comment by rmottola** [comment]
@jasonliul it is not a matter of ambition, but realism. I cannot support platforms I am unable to compile myself on. AF is currently a one-man show, with some help by @roytam1 who does the best doing builds.
Also the future is dim: the more Firefox diverges, the harder it is to maintain ArcticFox (see the excellent SeaMonkey)

Yes, there is interest for ArcticFox. I believe it stems from two main reasons

1. interest in the classic UI compared to the ever-changing Firefox which is just a bad copy of Chrome and is everytime worse (I hate the latest menus, even the look of these rounded things).
2. continuous drop for older platforms. I can understand Bing or Safari, they follow main OS cycles, but Firefox could be a step forward an be "free" for OpenSource, instead it drops excellend Windows 7 and MacOS 10.13... while with some effort it could prove to be different. It could even be considered "eco-firendly" not insisting in device obsolescence.
3. use of the rustc language

So essentially it is an issue with decisions of Mozilla, which is very google and very company and not a user-friendly open source project, Yet it is irrelevant compared to 5 years ago!

**Comment by rmottola** [comment]
> > No, I don't mind, I think it is convenient for users.
> 
> uploaded to my server: http://o.rthost.win/gpc/files1.rt/arcticfox-43.0.win32-git-20231027.7z

as always, Thanks Roy.... uploaded.
