### ISSUE TITLE
Unable to use Youtube timeline

### ISSUE THREAD

**Issue by louies0623** [rmottola/Arctic-Fox#166]
Timeline not working when using Youtube.

Mac 10.13

**Comment by rmottola** [comment]
What do you mean "not working"? does not update or is not interactive?

The default is to open YouTube in mobile mode, it was done by wickinx long time ago. The new interface is extremely heavy on older systems and on PPC it hangs.
Maybe mobile version is supposed not to have it editable, but display only.

However you can go in about:config you can tweak the user agent for youtube. Try the desktop version and let me know.
I have tried the desktop version on 10.6 and 10.7 and I can skip back and forward as expected.

**Comment by rmottola** [comment]
@louies0623 would you mind checking which YT version you are using?
YT support is hard.
I tested on current dev branch and things work as I describe. To force desktop version, please go into about:config and set the useragent. See also this issue: https://github.com/rmottola/Arctic-Fox/issues/141

Read more here: https://github.com/rmottola/Arctic-Fox/wiki/Known-Websites-issues

**Comment by rmottola** [comment]
@louies0623 could you tell me more? and please update to 43.1 in the meanwhile

**Comment by rmottola** [comment]
@louies0623 https://github.com/rmottola/Arctic-Fox/issues/194 ?
