### ISSUE TITLE
Pages of the new tab are messed up.

### ISSUE THREAD

**Issue by louies0623** [rmottola/Arctic-Fox#167]
When opening a new tab, the pages of the new tab are messed up.

Mac 10.13

**Comment by rmottola** [comment]
@louies0623 do you refer to the fact that the search box is squeezed at left and not working? Or something else broken?

**Comment by louies0623** [comment]
Yes, the search box is squeezed to the left.

**Comment by rmottola** [comment]
I fixed this to a decent level in current dev branch. except for this detail remaining: https://github.com/rmottola/Arctic-Fox/issues/175

**Comment by rmottola** [comment]
Did you test, perhaps, @louies0623 ?

**Comment by rmottola** [comment]
Current dev is even a little better than 43.1, I would close the issue

**Comment by louies0623** [comment]
It has been fixed, but the displayed web page record does not have a delete button.
