### ISSUE TITLE
The search buttons on the main screen and new tab do not respond.

### ISSUE THREAD

**Issue by louies0623** [rmottola/Arctic-Fox#168]
I pressed the search button on the home screen and the new tab, but there was no response.
Search engines that users can choose should also be added to the search box.

Mac 10.13

**Comment by rmottola** [comment]
That is a known issue,that exists since a long time, didn't track it though.
Toolbar search component works fine though, so this is low priority

**Comment by rmottola** [comment]
Current git master&dev have a fix for that.

**Comment by rmottola** [comment]
@louies0623 does it work for you now in 43.1?

**Comment by louies0623** [comment]
Is work
