### ISSUE TITLE
installation Failure V.43 and V.42 with Mac Pro  2,1 running 10.6.8

### ISSUE THREAD

**Issue by Bocheh** [rmottola/Arctic-Fox#170]
Hope this provides the info needed to assist with resolution. My first visit to this site.

**install attempt with V.43 64 byte**

Process:         arcticfox [1047]
Path:            /Volumes/Arctic Fox/ArcticFox.app/Contents/MacOS/arcticfox
Identifier:      org.mozilla.arctic fox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [125]

Date/Time:       2023-11-30 21:19:31.909 -0700
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          27278 sec
Crashes Since Last Report:           62
Per-App Crashes Since Last Report:   5
Anonymous UUID:                      01EE424B-766F-4A11-B8D2-11BE5AC3D1E1

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/Arctic Fox/ArcticFox.app/Contents/MacOS/arcticfox
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3bdef  dyld 132.1 (???) <DB8B8AB0-0C97-B51C-BE8B-B79895735A33> /usr/lib/dyld

Model: MacPro2,1, BootROM MP21.007F.B06, 8 processors, Quad-Core Intel Xeon, 3 GHz, 19 GB, SMC 1.15f3
Graphics: ATI Radeon X1900 XT, ATY,RadeonX1900, PCIe, 512 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x87), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en2
PCI Card: ATY,RadeonX1900, sppci_displaycontroller, Slot-1
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: ST3750640AS, 698.64 GB
Serial ATA Device: ST3750640AS P, 698.64 GB
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
USB Device: SanDisk 3.2Gen1, 0x0781  (SanDisk Corporation), 0x5583, 0xfd100000 / 2
USB Device: Hub, 0x05ac  (Apple Inc.), 0x911c, 0xfd300000 / 3

**Install Attempt with v.43 32 bit**

Process:         arcticfox [1192]
Path:            /Volumes/Arctic Fox 1/ArcticFox.app/Contents/MacOS/arcticfox
Identifier:      org.mozilla.arctic fox
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  launchd [125]

Date/Time:       2023-11-30 21:25:04.823 -0700
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          27610 sec
Crashes Since Last Report:           63
Per-App Crashes Since Last Report:   6
Anonymous UUID:                      01EE424B-766F-4A11-B8D2-11BE5AC3D1E1

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/Arctic Fox 1/ArcticFox.app/Contents/MacOS/arcticfox
  Reason: image not found

Binary Images:
0x8fe00000 - 0x8fe4162b  dyld 132.1 (???) <283EE026-C0FE-1FF9-DB81-BFB155793157> /usr/lib/dyld

Model: MacPro2,1, BootROM MP21.007F.B06, 8 processors, Quad-Core Intel Xeon, 3 GHz, 19 GB, SMC 1.15f3
Graphics: ATI Radeon X1900 XT, ATY,RadeonX1900, PCIe, 512 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x87), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en2
PCI Card: ATY,RadeonX1900, sppci_displaycontroller, Slot-1
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: ST3750640AS, 698.64 GB
Serial ATA Device: ST3750640AS P, 698.64 GB
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
USB Device: SanDisk 3.2Gen1, 0x0781  (SanDisk Corporation), 0x5583, 0xfd100000 / 2
USB Device: Hub, 0x05ac  (Apple Inc.), 0x911c, 0xfd300000 / 3
USB Device: Apple Cinema HD Display, 0x05ac  (Apple Inc.), 0x921c, 0xfd320000 / 4
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8206, 0x5d200000 / 2
USB Device: Hub in Apple Pro Keyboard, 0x05ac  (Apple Inc.), 0x1002, 0x5d100000 / 3
USB Device: USB Receiver, 0x046d  (Logitech Inc.), 0xc534, 0x5d130000 / 5
USB Device: Apple Pro Keyboard, 0x05ac  (Apple Inc.), 0x0204, 0x5d110000 / 4
FireWire Device: built-in_hub, Up to 800 Mb/sec
FireWire Device: unknown_device, Unknown

**Install attempt V.42**

Process:         arcticfox [1047]
Path:            /Volumes/Arctic Fox/ArcticFox.app/Contents/MacOS/arcticfox
Identifier:      org.mozilla.arctic fox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [125]

Date/Time:       2023-11-30 21:19:31.909 -0700
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          27278 sec
Crashes Since Last Report:           62
Per-App Crashes Since Last Report:   5
Anonymous UUID:                      01EE424B-766F-4A11-B8D2-11BE5AC3D1E1

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/Arctic Fox/ArcticFox.app/Contents/MacOS/arcticfox
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3bdef  dyld 132.1 (???) <DB8B8AB0-0C97-B51C-BE8B-B79895735A33> /usr/lib/dyld

Model: MacPro2,1, BootROM MP21.007F.B06, 8 processors, Quad-Core Intel Xeon, 3 GHz, 19 GB, SMC 1.15f3
Graphics: ATI Radeon X1900 XT, ATY,RadeonX1900, PCIe, 512 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x87), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en2
PCI Card: ATY,RadeonX1900, sppci_displaycontroller, Slot-1
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: OWC Mercury Electra 3G SSD, 931.51 GB
Serial ATA Device: ST3750640AS, 698.64 GB
Serial ATA Device: ST3750640AS P, 698.64 GB
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
Parallel ATA Device: PIONEER DVD-RW  DVR-118L
USB Device: SanDisk 3.2Gen1, 0x0781  (SanDisk Corporation), 0x5583, 0xfd100000 / 2
USB Device: Hub, 0x05ac  (Apple Inc.), 0x911c, 0xfd300000 / 3

**Comment by rmottola** [comment]
As the error message says, it can't find libc++
I suppose you don't have lmacports installed.

Current ArcticFox builds are build in a MacPorts environment and not relinked extra, so you need to install libc++ extra.
Since I read you have a 64bit CPU, use libc++.from.MP.10.6.mac64.zip, which is provided for your convenience for 42.1 and 43.0 releases.
Just expanding it into /usr/lib should do. Please report back

**Comment by Bocheh** [comment]
Thanks for the response. I am unclear where I find libc++ extra?
Maybe you could provide me some instructions to follow.

**Comment by Bocheh** [comment]
I found these instructions searching the web. Is this what I need to do to install Libc++extra???


Start in a safe place.

$ mkdir libcxx
$ cd libcxx
Special for Mac OS X 10.6: LLVM's C++ Standard Library ABI, [libc++abi](http://libcxxabi.llvm.org/), is not included with Snow Leopard. You must install it yourself.

$ wget http://home.roadrunner.com/~hinnant/libcppabi.zip
$ unzip libcppabi.zip
$ sudo cp cxxabi.h        /usr/include
$ sudo cp libc++abi.dylib /usr/lib
Check out.

$ svn co http://llvm.org/svn/llvm-project/libcxx/trunk source
Build.

$ cd source/lib
$ export TRIPLE=-apple-
$ export MACOSX_DEPLOYMENT_TARGET=10.6 # special for Mac OS X 10.6
$ ./buildit
Install.

$ cd /usr/lib
$ sudo ln -s path/to/libcxx/source/lib/libc++.1.dylib
$ sudo ln -s libc++.1.dylib libc++.dylib
$ cd /usr/include/c++
$ sudo ln -s path/to/libcxx/source/include v1

**Comment by rmottola** [comment]
@Bocheh no, wait... your instructions look very complicated and do a build from source. Given that, you are better off just using MacPorts which automates it for you!

Just go in the releases, open the Asset sections (for old browser there is a link provided, since it won't open otherwise) and there you find it. It is where you have gotten ArcticFox (or did you get it elsewhere?)

43 release:  https://github.com/rmottola/Arctic-Fox/releases/tag/v43.0
43 Assets: https://github.com/rmottola/Arctic-Fox/releases/expanded_assets/v43.0

**Comment by Bocheh** [comment]
Yes that is where I got ArticFox. I have downloaded the Libc++ zip file. What must I do next with the zip file now that I have it on a usb drive plugged into my MacPro?

**Comment by Bocheh** [comment]
I tried installation again with the libc++ zip file in the sys lib.
got the same error.
Process:         arcticfox [978]
Path:            /Applications/ArcticFox.app/Contents/MacOS/arcticfox
Identifier:      org.mozilla.arctic fox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [143]

Date/Time:       2023-12-05 08:12:04.439 -0700
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          68589 sec
Crashes Since Last Report:           70
Per-App Crashes Since Last Report:   12
Anonymous UUID:                      01EE424B-766F-4A11-B8D2-11BE5AC3D1E1

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Applications/ArcticFox.app/Contents/MacOS/arcticfox
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3bdef  dyld 132.1 (???)
<DB8B8AB0-0C97-B51C-BE8B-B79895735A33> /usr/lib/dyld

**Comment by Bocheh** [comment]
I download directly  to My Mac Pro the two links you provided. I  attempted the install of Ver. 43 and got the same error.
expanded the zip file in the user library it displayed two other files.

**Comment by Bocheh** [comment]
I open the files in terminal that were in the zip file libc++ and I get the
following info. Don't know if that is telling us anything .

Last login: Tue Dec  5 08:28:32 on ttys000
/Users/henrybochenski/Library/libc++.from.MP.10.6.mac64/libc++.1.dylib ;
exit;
henry-bochenskis-computer-3:~ henrybochenski$
/Users/henrybochenski/Library/libc++.from.MP.10.6.mac64/libc++.1.dylib ;
exit;
-bash:
/Users/henrybochenski/Library/libc++.from.MP.10.6.mac64/libc++.1.dylib:
cannot execute binary file
logout

[Process completed]

**Comment by rmottola** [comment]
@Bocheh oh wait, libraries are not supposed to be executed. Libraries need to be in a place where they are commonly found.
Since you don't have macports, you will not have /opt/local/lib I suppose. I don't think /Users/henrybochenski/Library/ will work, because that is for "Mac" frameworks and kits, but here we are at "unix level" with a C++ library.

Put the libraries in /usr/lib thus. I suppose you are setup to to have write permissions there?

For the "Finder way". Try in the finder "Go to Folder" and enter "/usr/lib" this will open a window with the usually hidden system folder. Just move by dragging the unzipped files to it. It will ask you to authenticate.

Or for the unix way try the following, in a Terminal:

```
cd /usr/lib
sudo unzip <path to downloaded libc++.from.MP.10.6.mac64.zip>
<enter your user password if requested>
```

Alternatively, move the files from where you put them into /usr/lib. `sudo mv <filename> /usr/lib` should do it. Repeat for both files.

**Comment by Bocheh** [comment]
That did the trick. Thank you some much for your patience and support.
Is there anything else I should know or do going forward?

**Comment by Bocheh** [comment]
question when I do an internet search it says its using Yahoo. Is that correct?
2nd thing an example of what happens from some random sites I would normally use.
www.coppercanyongolfclub.com
when I enter the site above in the search bar it opens the landing page but if I click on any tabs link tee times a pulsating large dot appears in the center of my screen and nothing else.

**Comment by rmottola** [comment]
Strange, the default search engine is DuckDuckGo, you can select it in the search field top-right.
[www.coppercanyongolfclub.com](http://www.coppercanyongolfclub.com/) doesn't load in ArcticFix, most probably it requires too recent JavaScript or DOM stuff.. It doesn't load for me in FireFox 119 either, but it does in SeaMonkey.
if you an browse e.g. wikipedia and even load google.com. then I this issue can be closed, @Bocheh - you got v43.0 working

PS: which of the copy& tricks did you use?

**Comment by Bocheh** [comment]
I used the finder method and it work great.
Thanks again for all your help. It's appreciated.

**Comment by Bocheh** [comment]
I used the finder method and it work great.
Thanks again for all your help. It's appreciated.

**Comment by rmottola** [comment]
Fine! I hope ArcticFox will be useful for you. Already working on the next release, I was able to squeeze in a lot of more fixes @Bocheh , stay tuned.
Unfortunately, currently I am essentially alone on this project.
