### ISSUE TITLE
layout of web pages is all wrong in v.43

### ISSUE THREAD

**Issue by jochemvdberge** [rmottola/Arctic-Fox#180]
After managing to get v.43 working on Mac OS X 10.6.8 (had to install the libc++ dependency) I`m happily typing in Articfox (and finally having a modern browser on this old Mac) but the layout of multiple websites seems to be completely wrong. I've included some examples with this issue. Although I can now access more websites than before most of them look weird.
![windows-1252''Capture dcran 2023-12-31 14 41 33](https://github.com/rmottola/Arctic-Fox/assets/28038304/bd01fa0a-d235-4ec8-931e-8e17c21de956)

**Comment by jochemvdberge** [comment]
as an addition:some websites report that JavaScript is disabled but when I check about:config the setting for javascript.enabled is true

**Comment by Veemyu** [comment]
Do you have a menu bar on 10.6.8 with v43?
I don't have it. That's why I downgraded back to 42.1
![Screen shot 2024-01-01 at 3 00 21 PM](https://github.com/rmottola/Arctic-Fox/assets/38016914/52dfb6fa-0ca0-4492-850c-004e660af592)
![Screen shot 2024-01-01 at 2 59 16 PM](https://github.com/rmottola/Arctic-Fox/assets/38016914/13fad265-c4a7-414e-88ae-579c343ee55c)

**Comment by jochemvdberge** [comment]
I'll have to check that when I have access to the machine again, but as far as I remember I did have a menu bar. But it could be a good idea to downgrade back to 42.1. Will give that a try when I can.

**Comment by rmottola** [comment]
I just think you are hitting some ArcticFox limits, if you are testing GitHub, essentially loose your hope except with uber-latest Firefox or Chrome.

So if there is a website which rendered in 42.x and not in 43.x, I am eager to know and see, but otherwise... it is just a limit of ArcticFox. As you notice it is improving, but that is all.

**Comment by rmottola** [comment]
> Do you have a menu bar on 10.6.8 with v43? I don't have it. That's why I downgraded back to 42.1 

Others have reported this issue. I did not have issues with 10.6 though. Could you test 43.1 in the meanwhile? It works fine for me.
In any case, upgrade to 43.1, it is quite improved IMO, although don't expect miracles.

**Comment by rmottola** [comment]
@Veemyu tried 43.1 ?

**Comment by rmottola** [comment]
No reply from original poster.. The menu bar issue is fixed for me and got no reply on that either.
github.com "will never work" on AF nor on most non-mainstream browsers, they are just too eager to break things. SeaMonkey is broken and now even old FF78 which from 10.11 is broken, worked until some weeks ago. Ditto for safari, renders the first page, but then all commit pages are blank.

For other sites, specific bug reports which can be analyzed and tagged eventually.

**Comment by jochemvdberge** [comment]
hi @rmottola , my apologies for never getting back to you. The notification seems to have been drowned between all of my other Github notifications (I do use it for work too). As for the original issue: Unfortunately I don't have physical access to the machine for a while yet (it is located somewhere in the middle of nowhere with in-laws) so I either have to reach out for someone to update the machine or get there myself (probably not before mid-May or the summer holiday period). Thanks for the tip about Github, I'll stop using that as a reference if I do run into future issues :-).

**Comment by rmottola** [comment]
@jochemvdberge try latest v45! it renders github much better - testifying improvement.
Still, GitHub has issues due to JavaScript with most browsers, as written..
