### ISSUE TITLE
Feature request: youtube trackbar allow to seek by single click

### ISSUE THREAD

**Issue by JoachimHenze** [rmottola/Arctic-Fox#194]
I am not using ArcticFox myself, but I do use
roytams "New Moon 27" https://rtfreesoft.blogspot.com/
which is also a Palemoon27-fork, and which frequently pulls the changes from ArcticFox into its sources.
"New Moon 27" unfortunately has no own bugtracker, so I dare to use yours.

When playing a video in youtube.com, assuming the user wants to jump to another location of the video.
Currently the trackbar must be dragged at the cursor where the currents-video-playback position is to the new position, instead of being able to click on a specific video position only by a single click within the trackbar.

![arctic fox](https://github.com/rmottola/Arctic-Fox/assets/33393466/1d1b3677-eacb-4d76-b11b-4848b30f636a)

I know that other browsers like "New Moon 28" do that better, but their performance is not on par with "New Moon 27" unfortunately, regarding navigating on youtube in general. Therefore the request to "port back" that detail.

**Comment by JoachimHenze** [comment]
This may depend on the mobile vs. desktop mode. And therefore slightly relates to https://github.com/rmottola/Arctic-Fox/issues/141
Ftr: I don't want it to become slower / more heavy-weight! The mobile-version is what makes ArticFox and NewMoon 27 so performant on youtube, I guess. I do like that.


To force the desktop version in about:config the user agent string general.useragent.override.youtube.com to e.g. Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20010101 Goanna/43.0 Firefox/48.0 ArcticFox/43.0
Indeed, with that override, the seeking works like I do requested it here, but youtube.com in general becomes unbearable slow then.

Well I do assume, the only way to improve the situation then is to improve the browsers performance with the youtube.com-desktop version.

**Comment by rmottola** [comment]
@JoachimHenze there is no silver bullet, the mobile version is faster but lacks features, if you want all features, you need the desktop version, but have the downside of it being slower. No way I can "fix" that :)
Furthermore certain features of the desktop versions don't work because of JS limitation, so I prefer not getting tons of bug reports I would not be able to resolve.

Then, it depends on your hardware and expectation. Google puts a lot of bloat in the full version, still playing videos is acceptable even on older Core2 and Core machines... so depends.

**Comment by rmottola** [comment]
Actually, I tested on a usable old system Pentium-M 2.26Ghz and AMD Radeon, even with the mobile mobile version I an seek in the timeline (current dev version, upcoming v44) by clicking, Sometimes the click is not captured, but click-drag of the thumb always work. So seeking is quite possible also in that version.
So your choice of mobile vs. desktop, but seeking is always possible.
