### ISSUE TITLE
Crash after startup under Mac OS X 10.6.8; MacPorts installed, tried copying files from archive

### ISSUE THREAD

**Issue by slavalisoff** [rmottola/Arctic-Fox#206]
[Here's the crash log (Pastebin)](https://pastebin.com/uEBKJv2w)
My OS isn't in English. I have MacPorts installed, also tried copying libraries from the archive. I've downloaded both app and libraries for x64. My system is x64. Also tried installing x86 libraries and using x86 app, but the result was same

Hardware: iMac 24" (early 2009). 2.66 GHz Core2Duo, 8 gigs of RAM and NVidia 9400M GPU with 256MB shared VRAM

I can provide additional information if needed

**Comment by Randrianasulu** [comment]
```
Symbol not found: ___emutls_get_address
```

Ah, on emulated (qemu/kvm) 10.6.8 x64 I get same error :)

**Comment by Randrianasulu** [comment]
@slavalisoff I tried to install ports, installer hanged on tclsh script for few hours. killed script, run 'port selfupdate' and 'sudo port install libcxx' - after  this arctic fox started up!

**Comment by slavalisoff** [comment]
I've tried to compile ArcticFox from sources, but my build didn't launched. However, when after that I tried to launch the official build it launched and worked well without any crashes.

**Comment by rmottola** [comment]
> [Here's the crash log (Pastebin)](https://pastebin.com/uEBKJv2w) My OS isn't in English. I have MacPorts installed, also tried copying libraries from the archive. I've downloaded both app and libraries for x64. My system is x64. Also tried installing x86 libraries and using x86 app, but the result was same
> 
> Hardware: iMac 24" (early 2009). 2.66 GHz Core2Duo, 8 gigs of RAM and NVidia 9400M GPU with 256MB shared VRAM
> 
> I can provide additional information if needed

With macports installed, you don't need the extra libraries... maybe remove them? I literally archived those from macports.

**Comment by rmottola** [comment]
> @slavalisoff I tried to install ports, installer hanged on tclsh script for few hours. killed script, run 'port selfupdate' and 'sudo port install libcxx' - after this arctic fox started up!

Maybe some MacPorts issue.. but now you have the libraries and are ready to go. Happy that it works!

**Comment by rmottola** [comment]
> I've tried to compile ArcticFox from sources, but my build didn't launched. However, when after that I tried to launch the official build it launched and worked well without any crashes.

MacPorts did provide you the libraries. So all is set. i don't know why mine didn't work... but that's not the clue.

Maybe your build doesn't work because of some configure option... or the way you built/launched it.
Does build really succeed completely? From console then do "mach run" after "mach build", it should startup  without packaging.

**Comment by rmottola** [comment]
I notice in your stackTrace libCyrillicConverter
Do you use Russian/Serbian/Ukrainian/Bulgarian/etc?
How is your Language setup? and your input?

While I imported quite some patches from Firefox... I didn't test language beyond English nor different inputs.

**Comment by Randrianasulu** [comment]
In theory macports can create dmgs for (i think) libcxx - see section 3.4.2 at https://guide.macports.org/#development

Not sure if githab can easily automate this ....

**Comment by rmottola** [comment]
Things work for you now?

Do you want to compile from sources? That would allow you to track github dev in case you wish.

**Comment by Randrianasulu** [comment]
@rmottola not sure if last reply was for me ... but howmuch space non-debug source build takes and can I run it (outside of macports system?) on separate virtual hdd? (due to lack of space on main system hdd. Even if qemu-img allow to resize disk image I can't convince macos into expanding hfs+ native fs)

**Comment by rmottola** [comment]
@Randrianasulu question was actually for OP @slavalisoff 
A check on my Mac the complete space needed for github sources + completed build is 4.6 GB
Build directory itself is 3.1 G

**Comment by rmottola** [comment]
No further answer and it appeared working. Open a new, more specific bug in case, possibly with the upcoming release!

**Comment by rmottola** [comment]
@slavalisoff @Randrianasulu reading https://github.com/rmottola/Arctic-Fox/issues/214 should show that I included the wrong files. Please try the libc++ from v45.1 and let me know.
