### ISSUE TITLE
Can't read https://www.france24.com

### ISSUE THREAD

**Issue by InfoLibre** [rmottola/Arctic-Fox#222]
404 error when looking at https://www.france24.com.
Windows XP SP3 in Virtualbox, Artic Fox 44.0.

**Comment by rmottola** [comment]
v45.1 on linux works. So either it is v44 or it is a windows specific issue... Windows builds are provided by courtesy of @roytam1 . Let's ask him for a v45.1 build and test.

**Comment by InfoLibre** [comment]
I can provide the Windows XP image for Virtualbox I used to make tests, if necessary.

**Comment by rmottola** [comment]
I miss Visual studio 2013 or 2015 to compile stuff, I concentrate on Linux, Mac, BSD... and leave others to build windows!

**Comment by roytam1** [comment]
today's win32 build for testing (could be buggy)
[arcticfox.7z.001.zip](https://github.com/user-attachments/files/17212448/arcticfox.7z.001.zip)
[arcticfox.7z.002.zip](https://github.com/user-attachments/files/17212490/arcticfox.7z.002.zip)

**Comment by InfoLibre** [comment]
I can't extract these files. I can unzip them but after, it doesn't work.

**Comment by roytam1** [comment]
use 7-zip to open .001 file to extract

**Comment by InfoLibre** [comment]
I know. But after unzipping files,  .001 and .002 files can't be opened, even after renaming them into .7z files.

![image](https://github.com/user-attachments/assets/4e18c4bf-e769-45cc-84ae-c48631338961)

**Comment by roytam1** [comment]
> even after renaming them into .7z files.

don't rename, keep .001 and .002
![image](https://github.com/user-attachments/assets/030316bf-3882-406f-8f71-cec9291b021b)

**Comment by InfoLibre** [comment]
Even without renaming them, there's the same error.

**Comment by roytam1** [comment]
> Even without renaming them, there's the same error.

then you may need to update your 7-zip installation,

**Comment by InfoLibre** [comment]
I don't think I've got an old version on Linux Mint. None of the tools I tried works with your files.

**Comment by roytam1** [comment]
my older p7zip-16.02 also works so I don't know what you did.
![image](https://github.com/user-attachments/assets/3b7062f2-457b-48ae-8bfe-c9140d682a3d)

**Comment by InfoLibre** [comment]
Same error with https://wiki.gnome.org/Apps/FileRoller.

I tried under Windows 10 with last version of 7-Zip. I can extract .001 file but not .002 file:

![image](https://github.com/user-attachments/assets/519954c0-59f6-4648-9850-ed652b696ec8)

**Comment by InfoLibre** [comment]
Artic Fox (001 file) under Windows XP SP3:

![image](https://github.com/user-attachments/assets/7b34b347-a402-4110-bbc6-a8f20c8a3af4)

**Comment by rmottola** [comment]
> today's win32 build for testing (could be buggy) [arcticfox.7z.001.zip](https://github.com/user-attachments/files/17212448/arcticfox.7z.001.zip) [arcticfox.7z.002.zip](https://github.com/user-attachments/files/17212490/arcticfox.7z.002.zip)

is it latest dev, so "newer" than release?

**Comment by rmottola** [comment]
I tried on Windows 7. 001 expands, 002 says "Cannot open file as Archive".
I get a 91MB big folder, if I launch arcticfox it dies VCOM120.DLL is missing. I suppose it is in the 002 part?

**Comment by roytam1** [comment]
> is it latest dev, so "newer" than release?

yeah.

> if I launch arcticfox it dies VCOM120.DLL is missing. I suppose it is in the 002 part?

`mach package` doesn't copy this from VC redist folder, you may grab one of my NM27 package to extract this. (or install VC2013 runtime)

**Comment by InfoLibre** [comment]
Even with VC2013, I've got the XML parsing error:

![Capture d’écran du 2024-10-03 07-54-31](https://github.com/user-attachments/assets/b0a7c509-4f1c-4a10-906d-29d1e680c6c8)

**Comment by roytam1** [comment]
> Even with VC2013, I've got the XML parsing error:

thats another issue

**Comment by rmottola** [comment]
With the dll gotten from an older zip you sent me, ArcticFox 45.1 starts!
I have no XML issues, perhaps because that one is only during migrations, I skipped it and did run ArcticFox before.

france24 appears to work here on win7
![image](https://github.com/user-attachments/assets/d3c655fe-ff35-403e-bb9d-1a1d2f87e5b2)

Generally things seem fine... even WebGL and YouTube plays... not bad.

**Comment by InfoLibre** [comment]
Indeed. Same result on my XP VM.

**Comment by roytam1** [comment]
> Artic Fox (001 file) under Windows XP SP3:
> 
> ![image](https://private-user-images.githubusercontent.com/3955499/373008451-7b34b347-a402-4110-bbc6-a8f20c8a3af4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQyMzAsIm5iZiI6MTcyNzk1MzkzMCwicGF0aCI6Ii8zOTU1NDk5LzM3MzAwODQ1MS03YjM0YjM0Ny1hNDAyLTQxMTAtYmJjNi1hOGYyMGM4YTNhZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTExMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FmOGRlM2UyOWMwZDNiMTYzZjNlODgyOWQ1MzY0OGRkNGIzZmFlYTZiMDNmYzMwN2NlZDZiZDYxNTk3OWY4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6ncd-GSVVrBCp0I7hA8zCsa84cSuMeninpo_jCUviIU)

it is fixed in my tree: https://github.com/roytam1/Arctic-Fox/commit/4627916138ac6cf9c3be0de221c2b64cde1588bc

**Comment by rmottola** [comment]
> it is fixed in my tree: [roytam1@4627916](https://github.com/roytam1/Arctic-Fox/commit/4627916138ac6cf9c3be0de221c2b64cde1588bc)

fixed officially with "Bug 1179346 - Add strings and accesskeys for Microsoft Edge. r=mak"

**Comment by rmottola** [comment]
So can we consider the original bug closed? It works now.
We just need a new release in plain ZIP format 45.1 .. or do we need 45.2 for XP?
