### ISSUE TITLE
Arctic Fox 27.12.0 crashes on OS 10.6.8 - starting with a fresh profile does not help

### ISSUE THREAD

**Issue by verdant1068** [rmottola/Arctic-Fox#53]
Hi Riccardo

Arctic Fox v12 crashes instantly and repeatedly (even after 6 attempts, a 'refresh' dialog never appears) on my 10.6.8 system. Removing the old profile does not help either. I have attached the Apple generated crash report.
Thanks verdant1068
[ArcticFox v12 Crash Report on OS X 10.6.8.txt](https://github.com/rmottola/Arctic-Fox/files/7106111/ArcticFox.v12.Crash.Report.on.OS.X.10.6.8.txt)

**Comment by rmottola** [comment]
sorry from the Stacktrace I can't tell. I didn't build and test myself this release on mac, it was prepared by @wicknix. Maybe he can tell about test on his system.

**Comment by verdant1068** [comment]
Hi Riccardo,

Thanks for replying promptly. I wil ask wicknix what he can make of the
Stacktrace.

**Comment by wicknix** [comment]
Same as the last few Mac releases. Initial crash upon upgrade on some machines. Other machines the upgrade went fine. It seems random. Force reopening multiple times "usually" gives you a "refresh" dialog box, or a "start in safe mode / reset to defaults" prompt. So far i've gotten every release to eventually work with a new profile, but that's not how it should be. It does not seem to be an issue with other OS's (win32/linux) and nothing has changed on my build machine so i know it's not that. I suppose i could try building with different mozconfig options and see if the results vary as it's been almost a year since the last release, which i believe had the same issue, and a few releases before that did as well.

Another option would be having @rmottola do a mac build and upload it for testing as we use different build environments and configs. If the issue persists it at least eliminates my build machine and/or mozconfig. Either way, i'll see if i can make heads or tails of the crash report.

Cheers

**Comment by verdant1068** [comment]
Thanks. Please let me know if and when you want me to run any trial
re-builds etc.

**Comment by rmottola** [comment]
I remember having a similar issue many months ago. Unfortunately not all data is inside the profile, there is some specific MacOS data: in your user Preferences folder, there is a file called org.mozilla.arctic fox.plist (with or without space... maybe both). Move it asid or trash it.

**Comment by verdant1068** [comment]
Thanks for your suggestion. It did not solve the issue but appears to point
to it. When I removed the org.mozilla.arctic fox.plist file from my User
Preferences folder, running AF 27.11 recreated it and AF l27.11 launches
and functioned as normal. However, when again removing org.mozilla.arctic
fox.plist file from my User Preferences folder and trying to run AF 27.12,
it still crashes repeatedly.

The problem appears to be that AF 27.12 is not creating a functioning
org.mozilla.arctic fox.plist i.e. no new org.mozilla.arctic fox.plist
appears in my User Preferences folder......

**Comment by wicknix** [comment]
I think it's a 10.6 specific bug. Just did an 'upgrade' from 27.11 to 27.12 on Lion w/out a hiccup. I then backed up my profile and started fresh. No issue. Booted another machine running Lion, and again, no issue.

**Comment by rmottola** [comment]
> I think it's a 10.6 specific bug. Just did an 'upgrade' from 27.11 to 27.12 on Lion w/out a hiccup. I then backed up my profile and started fresh. No issue. Booted another machine running Lion, and again, no issue.

Appears so, but it is Strange. It happened me in the very past on Lion/10.7 though. This time it happened me on 10.6, but the trick I explained of removing those Mac preferences fixed. I suppose somehow windows or menus are registered that confuse the update. I am running happily on my 10.6 machine!

**Comment by rmottola** [comment]
I have a current build that works for me - but I don't know how to publish a file in this fork of project, since I have no releases.

**Comment by wicknix** [comment]
Hmm. Could you email it to me? I could then add it to the releases page. Otherwise you should be able to create a release in your repo. Then drop and drag the .dmg to it.

**Comment by rmottola** [comment]
How is release 39 regarding this issue? I had it not at the first start, but after a profile refresh, had to delete both the profile & preferences then it started, then it could manually import most relevant profile data (I just moved it aside). After the crash, I could start ArcticFox actually, but with not working bookmarks. Strange it happens exclusively on 10.6.
Current GIT dev branch should contain a possible fix. It needs to be tested preferably in a clean setup.

**Comment by verdant1068** [comment]
Unfortunately, release 39 is still crashing for me.......

**Comment by rmottola** [comment]
I am sorry... I was able to start 10.6 after some attempts and cleaning profile & preferences and all settings i found and since then it works. It works on 10.7 too.
39.0 does not contain some minor further tweaks though, I'lll do a 39.1 in a while.

**Comment by tingotanca** [comment]
Same pattern of repeated crashes as earlier in 10.6.8. Only one slight difference at the end:

**Comment by tingotanca** [comment]
Sorry, unable to post an image here. Its' here: https://forums.macrumors.com/threads/arctic-fox-web-browser-for-10-6-32-64-bit.2133051/post-30855236

**Comment by rmottola** [comment]
You know you are effectively running an AF with the "fix" that the plist in the Preferences does not get recreated.

**Comment by verdant1068** [comment]
Thanks Riccardo, I will try it as soon ***@***.*** releases it and report
back here.....
verdant

**Comment by tingotanca** [comment]
> I hope 39.1 provides improvement on this
It was 39.1

> the plist in the Preferences does not get recreated
After the procedure explained here
https://forums.macrumors.com/threads/arctic-fox-web-browser-for-10-6-32-64-bit.2133051/post-30827943
+ crashes and after that A.F. zeroed, the file 'org.mozilla.arctic fox.plist' had been re-created.

**Comment by verdant1068** [comment]
Hi Riccardo

With my 10.6.8 system,
I removed the full Arctic Fox folder located inside
/Users/username//Library/Application Support (containing the Profiles
folder) and the file org.mozilla.arctic fox.plist from
/Users/username/Library/Preferences.
I then launched AF 39.1, but the removed folder and plist file are not
recreated, and AF 39.1 crashes (which is just what happens with AF 39.0 and
AF 27.12.0 as well).
Whereas launching AF 27.11.0 creates the Arctic Fox folder containing
profiles.ini and the Profiles folder and contents, as well as creating the
org.mozilla.arctic fox.plist file, and so AF 27.11.0 runs without any
issues.

**Comment by rmottola** [comment]
>     * crashes and after that A.F. zeroed, the file 'org.mozilla.arctic fox.plist' had been re-created.

There is something strange there. It is not recreated for me and @verdant1068 reports it is not for him either.

**Comment by rmottola** [comment]
@verdant1068 sorry to hear that you still have issues. I don't, These crashes were never really fatal for me, a couple of restarts fixed them. Upgrade to 39.0 versions (my own compiled versions) required a more trials, but then it stabilized and after he fixes I had no more issues up to now. Test versions of upcoming 39.2 also continue to work...

**Comment by rmottola** [comment]
I continue building my development versions and they continue work fine on 10.6 and 10.7; thus for me the fix work. If it doesn't work for certain people, it could be to a certain setup on the system, certain differences. I am currently the only developer, so you need to understand this. Perhaps you have two systems to compare.  Does it work for other macforum people?

**Comment by rmottola** [comment]
@verdant1068 did you happen to try again on FreeBSD perhaps?

**Comment by rmottola** [comment]
Oh, happy to know it worked.
