### ISSUE TITLE
Sign in Youtube

### ISSUE THREAD

**Issue by Therodimus** [rmottola/Arctic-Fox#81]
Hi. First, you are doing a great job! Thank you. I use my old mac with snow leopard 10.6.8. So far everything is smooth except I can not sign in to any google services. (Not a big deal anyway) just to tell you. The input box is looping on email/phone. Can not continue for the next button...
Keep up the good Job.
Chris

**Comment by rmottola** [comment]
It completely broke even if you have a session stored and need to select the accounts and cannot.
Since the switch to workspace google broke most of older browser I fear.
Did you try FF45? PM27? just to compare and see if it is not a regression.

**Comment by rmottola** [comment]
Would you mind trying v40.0 or 40.1 and report back if it works? It does for me.

**Comment by ghost** [comment]
Just tried on my old Mac. Works great. But can't signin' to Github. Spinning endlessly. (I can signin' to another PC, download and import the dmg files to the Mac).
Good job. 
Thanks a lot. 
Chris
