### ISSUE TITLE
Task: to prevent data losing

### ISSUE THREAD

**Issue by JeanPaulLucien** [rmottola/Arctic-Fox#85]
Check and verify (on not).
https://github.com/JeanPaulLucien/MyPal-and-MyPaLbMa/issues/3

OS: Windows XP

**Comment by rmottola** [comment]
ArcticFox is not MyPal... why do you open the bug here? Also I don't fully understand. If you have more than one instance of your browser, they do all share the same profile - this is by design, PaleMoon and FireFox do the same.

**Comment by rmottola** [comment]
I am confused about which versions of the browser you are using here. This is Arctic Fox - we just changed the Folder path too, btw.
