### ISSUE TITLE
make-3d.ru: this connection is untrusted

### ISSUE THREAD

**Issue by JeanPaulLucien** [rmottola/Arctic-Fox#87]
Step to reptoduce:
1. Visit https://make-3d.ru

Result: This connection is untrusted message.
Expected result: site is opened.

OS: Windows XP

**Comment by rmottola** [comment]
The site indeed loads with current PaleMoon and SeaMonkey. Do we need some certificate update, @wicknix ? Try your browsers please.

**Comment by rmottola** [comment]
It works fine for me now on linux.
To be sure, @roytam1 can you update windows and test?

**Comment by roytam1** [comment]
> To be sure, @roytam1 can you update windows and test?

my plain build of AF works.
![image](https://github.com/rmottola/Arctic-Fox/assets/1192577/d9389644-7d6f-4c6f-a6ae-1b1673ab0bc1)

**Comment by rmottola** [comment]
Very well!
