### ISSUE TITLE
Arctic-Fox 39.0 crashes on Mac mini 2010 Server with Mac OS X 10.6.8 server

### ISSUE THREAD

**Issue by gbudny** [rmottola/Arctic-Fox#94]
Hi

This application crashes when I try to run it on Mac mini 2010 Server with Mac OS X 10.6.8 server. I can only see the information about this report:

https://gist.github.com/gbudny/bc6e1c15eb77a8d2ec058cb3adc4462e

Can you help me?

**Comment by wicknix** [comment]
The last few releases have been problematic on 10.6 specifically. Hopefully it'll get resolved soon. Your other options are download and use the older 27.9.11 ( link available in the wiki ) or use another browser like [InterWeb](https://github.com/wicknix/InterWebSnow/releases) in the meantime.

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I decided to use InterWeb and it works fine on Mac OS X 10.6.8 Server.

**Comment by rmottola** [comment]
For me, it works fine, once session data and preferences are thoroughly cleaned. Other reports not.
Please read more here: https://github.com/rmottola/Arctic-Fox/issues/53

39.2 will contain some more specific MacOS tweaks, maybe they will help.

**Comment by rmottola** [comment]
@gbudny please try 39.2 after cleaning preferences (not just profile). If you are no longer using it, then close the bug anyway. It works for me now.

**Comment by rmottola** [comment]
I found some specific issue on Mac and fixed it, it could fix this issue. It works for me (but I didn ot have the issue most of the times either). Would you mind testing 40.1?

**Comment by gbudny** [comment]
I checked the last version after cleaning my profile and preferences.
I don't see this bug anymore, so that was fixed.

I have issues with sound on YouTube, but I will have to create the another bug report.
